name: insight_med
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animated_text_kit: ^4.2.3
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  drop_down_list: ^2.0.0
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  intl: ^0.20.2
  logger: ^2.6.1
  meta: ^1.16.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utls/
  filename: app_images.dart

flutter:
  uses-material-design: true
  assets:
    - assets/images/
